language: node_js
branches:
  only:
    - master
    - production
before_install: "./build-env.sh"
deploy:
  - provider: firebase
  project: "staging-nearlywedded"
  on:
    branch: master
  - provider: firebase
  project: "nearlywedded-28143"
  on:
    branch: production
env:
  master: 
    - REACT_APP_API_PATH=https://us-central1-staging-nearlywedded.cloudfunctions.net/api/
  production:
    - REACT_APP_API_PATH=https://us-central1-nearlywedded-28143.cloudfunctions.net/api/